doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
      gedmo_tree:
        type: annotation
        prefix: Gedmo\Tree\Entity
        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
        alias: GedmoTree # (optional) it will default to the name set for the mapping
        is_bundle: false
      gedmo_loggable:
        type: annotation
        prefix: Gedmo\Loggable\Entity
        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
        is_bundle: false
    filters:
          softdeleteable:
            class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
            enabled: true
        
        #   gedmo_translatable:
        #     type: annotation
        #     prefix: Gedmo\Translatable\Entity
        #     dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
        #     alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
        #     is_bundle: false
        #   gedmo_translator:
        #     type: annotation
        #     prefix: Gedmo\Translator\Entity
        #     dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
        #     alias: GedmoTranslator # (optional) it will default to the name set for the mapping
        #     is_bundle: false
        #   gedmo_loggable:
        #     type: annotation
        #     prefix: Gedmo\Loggable\Entity
        #     dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
        #     alias: GedmoLoggable # (optional) it will default to the name set for the mapping
        #     is_bundle: false

stof_doctrine_extensions:
    orm:
        default:
          tree: true
          timestampable: false