security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
        super_admin_provider:
            memory:
                users:
                    env(SUPER_ADMIN_NAME): { password: '%env(SUPER_ADMIN_PASSWORD)%', roles: ['ROLE_ADMIN', 'ROLE_SUPER_ADMIN'] }
        all_users:
            chain:
                providers: ['app_user_provider', 'super_admin_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            form_login:
                login_path: security_login
                check_path: security_login
                enable_csrf: true
            logout:
                path: security_logout
                target: index_page
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
